{
 "title": "eBPF Application Monitoring Demo (K8s)",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Raw Connection Acceptance Events per Second (All)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (source_comm, source_ip, server_listen_port, dest_ip, dest_port) (rate(ebpf_connection_event_total[1m]))"
    }
   ]
  },
  {
   "title": "OrderService -> InventoryService Calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (source_app, dest_app) (\n  label_replace(\n    label_replace(\n      rate(ebpf_connection_event_total{source_comm=\"http-nio-8081-A\", source_ip=\"::ffff:10.244.0.67\"}[1m]),\n      \"source_app\", \"OrderService\", \"\", \"\"\n    ),\n    \"dest_app\", \"InventoryService\", \"\", \"\"\n  )\n)"
    }
   ]
  },
  {
   "title": "OrderService -> MySQL Calls (Simplified)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (source_app, dest_app) (\n  label_replace(\n    label_replace(\n      rate(ebpf_connection_event_total{source_comm=\"mysqld\", source_ip=\"::ffff:10.244.0.67\"}[1m]),\n      \"source_app\", \"OrderService\", \"\", \"\"\n    ),\n    \"dest_app\", \"MySQL\", \"\", \"\"  \n  )\n)"
    }
   ]
  },
  {
   "title": "InventoryService -> MySQL Calls (Simplified)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (source_app, dest_app) (\n  label_replace(\n    label_replace(\n      rate(ebpf_connection_event_total{source_comm=\"mysqld\", source_ip=\"::ffff:10.244.0.66\"}[1m]),\n      \"source_app\", \"InventoryService\", \"\", \"\"\n    ),\n    \"dest_app\", \"MySQL\", \"\", \"\" \n  )\n)"
    }
   ]
  },
  {
   "title": "External -> OrderService Calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (source_app, dest_app) (\n  label_replace(\n    label_replace(\n      rate(ebpf_connection_event_total{source_comm=\"http-nio-8080-A\", source_ip=\"::ffff:127.0.0.1\"}[1m]),\n      \"source_app\", \"External\", \"\", \"\"\n    ),\n    \"dest_app\", \"OrderService\", \"\", \"\" \n  )\n)"
    }
   ]
  }
 ]
}