# 1. Grafana Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring # Assumes 'monitoring' namespace already exists or is created by Prometheus file
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:10.4.0
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana
            - name: grafana-datasources-config
              mountPath: /etc/grafana/provisioning/datasources/datasource.yaml # 挂载到 Grafana 预期的位置
              subPath: datasource.yml # 指明 ConfigMap 中的哪个 key
            # Mount the dashboard provider config
            - name: grafana-dashboard-provider
              mountPath: /etc/grafana/provisioning/dashboards/dashboard-provider.yaml # 挂载到 Grafana 预期的位置
              subPath: dashboard-provider.yaml # 指明 ConfigMap 中的哪个 key
            # Mount the actual dashboard JSON
            - name: grafana-dashboard-json
              mountPath: /var/lib/grafana/dashboards/ebpf_demo_dashboard_k8s.json # 挂载到 dashboard provider 指定的路径
              subPath: ebpf_demo_dashboard_k8s.json # 指明 ConfigMap 中的哪个 key
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: admin
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: admin # !!! IMPORTANT: Change this in production
            # - name: GF_INSTALL_PLUGINS
            #   value: "grafana-piechart-panel"
      volumes:
        - name: grafana-storage
          emptyDir: {} # For demonstration, use emptyDir. For persistence, use a PersistentVolumeClaim.
            # Mount the datasource config
        - name: grafana-datasources-config
          configMap:
            name: grafana-datasources-config
        - name: grafana-dashboard-provider
          configMap:
            name: grafana-dashboard-provider
        - name: grafana-dashboard-json
          configMap:
            name: grafana-dashboard-json

---
# 2. Grafana Service (NodePort for external access)
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
spec:
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort